### PR TITLE
146 single neighborhood page make it responsive

### PR DESCRIPTION
**Pull request by radu-constantin**

### CODE REVIEW

**Review by nina-dk — CHANGES_REQUESTED** [review]
Excellent work! 💯 I didn't realize you'd handle the edit neighborhood, too. 🙌🏻

I didn't go over the code in detail at least for now. I only have a couple of observations for the UI and functionality:
- I got an error from React "react-jsx-dev-runtime.development.js:87 Warning: Each child in a list should have a unique "key" prop.". Because you render the `Col`s and the `Request`s that have the unique keys are nested. I fixed it temporarily by adding `key={request.id}` to the `Col`, too. Not sure if that's going to have any implications in the functionality, though, or even if can just ignore the warning.
- Right after submitting the Edit Neighborhood form, if I open up the modal again, it's not populated with the neighbourhood details as it is the other times.
- On Chrome and Safari, only 3 requests fit into a single row and plenty of empty space remains to the right. We could either reduce the gutters between the requests or their size a bit.
- I'd like there to be a little less padding/margin below each request's date.

Screenshot 2023-11-08 at 1 18 54 PM

**Comment by nina-dk** [comment]
Oh also, the neighborhood's title and icon remain gigantic and don't scale with the screen size.

**Comment by radu-constantin** [comment]
Thanks for the feedback Antonina! Your observations are on point. Will start working on some fixes.

**Comment by radu-constantin** [comment]
I've fixed the issues except for two of them.
1. I can't make the image scale without it losing its circle shape.
2. I'd like for the last request in a row to have no margins, but I don't know how I can achieve that.
Do you have any ideas on these issues?

**Review by nina-dk — CHANGES_REQUESTED** [review]
I still get the overflowing title and the extra space at the right of the page on Chrome and Safari.. I had to set the number of rows for `xl` screen size explicitly to get 5 columns in one row. Not sure what the issue is, but I can investigate further if you don't have chrome installed. 

For the title, I think the easiest fix is separating it from the icon into two columns. Something like:
```jsx
        <Col xs="2" className={styles.column}>
          <img className={styles.neighborhoodImg} src={neighborhoodImg} alt="Neighborhood" />
        </Col>
        <Col sm="10" className={styles.column}>
          <h1 className={styles.neighborhoodTitle}>{name}</h1>
        </Col>
```
Screenshot 2023-11-10 at 3 16 50 PM
Screenshot 2023-11-10 at 3 35 54 PM

**Review by nina-dk — APPROVED** [review]
Looks good 👌🏻

**Pull request merged**
