### PR TITLE
Create request form redo

### PR DESCRIPTION
**Pull request by nina-dk**
I updated the design for the create request form. I wanted to add [bootstrap form validation](https://react-bootstrap.netlify.app/docs/forms/validation/) but I couldn't for the life of me figure out how to do it using the react-router-dom `Form` component. If I revert to using react bootstrap's `Form` component, the request isn't made successfully. Let me know if you can find anything on this. It'd be nice to use it on all forms, but they're all built in the same way.

### CODE REVIEW

**Review by radu-constantin — APPROVED** [review]
Very thorough work, as usual!
I've presented my opinion on the issue that you encountered on discord.

**Comment by nina-dk** [comment]
Updates:

1. I'm using the react-bootstrap `Form` with `useSubmit` as suggested by @radu-constantin.
2. I added react's validation BUT there is an issue with the textarea element. I'm using `pattern` for the title to make sure it's not just whitespace, but there is no `pattern` property on `textarea`. So i had to do custom validation, which is kinda awkward. I wanted you all to check it out before i make the final styling changes to match our color palette because we might not want to implement it in this way, after all.

**Comment by radu-constantin** [comment]
Antonina, I think I've managed to solve the problem with the custom form-validation. I pushed directly to your branch since I thought it will be easier to see the exact changes I've made.
Hopefully I've understood the problem correctly. If not we can revert to the previous commit.

**Comment by nina-dk** [comment]
Nice! Thanks for this. However, we still need the custom validation for the `textarea`. If you try an input like "    " now, it will pass as valid and let you submit the form, but the request won't be created cause it fails on the backend (we need at least 4 non-whitespace characters). It'd be nice if we could figure out a way to display that more neatly, though. We don't have to revert, I'll add only the necessary code back in.

**Pull request merged**
