### PR TITLE
Reusable button components

### PR DESCRIPTION
**Pull request by nina-dk**
I created three separate button components based on styling. Let me know if you think that's too much. We could alternatively have one component and pass in the `variant` attribute as an argument each time.

### CODE REVIEW

**Comment by nina-dk** [comment]
Heads-up: I think that I've accidentally merged Radu's PR in mine so merging this into main probably means merging both.

**Comment by radu-constantin** [comment]
The buttons look good Antonina. If possible, yes I would like to have a single button component with a `variant` prop.
Then we can simply expand on the same component if we need to in the future.
We can document the component to see what each variant does by using this feature: https://code.visualstudio.com/docs/languages/javascript#_jsdoc-support
I think you've used it before, though I'm not sure. @MaxHass12 showed me this.

**Review by radu-constantin — CHANGES_REQUESTED** [review]
Good job Antonina. Can you integrate all the variants in a single Button Component?

**Comment by nina-dk** [comment]
I forgot to document the function like you said, but now that I think of it, with the `variant` types right above it, it feels pretty self-explanatory. Let me know if you think I should do it anyway.

**Comment by radu-constantin** [comment]
The comments are useful in the sense that if we hover over the place where you add the component, you can see the comments.
So you don't need to access the actual file where you declared the component.  
For example:  
Screenshot 2023-10-02 195723

**Pull request merged**
