### PR TITLE
124 re write single neighborhood page according to the new design

### PR DESCRIPTION
**Pull request by radu-constantin**

### CODE REVIEW

**Review by nina-dk — APPROVED** [review]
Great work, as always, Radu!

I propose we make the request search case-insensitive.
I also suggest the Edit button be more subtle and not take up that much space.
On the other hand, the title/desc section, as well as "Neighborhood requests" and the add request button could be more spaced out and wider imo.

**Comment by radu-constantin** [comment]
Thanks for the review Antonina! 
I've made the edit button a bit more subtle, though I'm not sure if this is how you meant it to be. I've also made the request search case insensitive (good catch).
As for the title and description, I would leave them as it is, since Neighborhoods can have longer descriptions that will take up a lot of space.
I did space out the Add Request button though.

**Comment by radu-constantin** [comment]
Thanks for the review Shwetank!
Great suggestions. I will go ahead and implement all of them!

**Comment by nina-dk** [comment]
I really like the separation of the components, great idea!

**Pull request merged**
